### ISSUE TITLE
Vagrant is broken

### ISSUE THREAD

**Issue by zvonimir** [smackers/smack#703]
I get this error when I do `vagrant up`:
```
    ubuntu: *** SMACK BUILD: Building SMACK ***
    ubuntu: -- The C compiler identification is GNU 9.3.0
    ubuntu: -- The CXX compiler identification is unknown
    ubuntu: -- Check for working C compiler: /usr/bin/cc
    ubuntu: -- Check for working C compiler: /usr/bin/cc -- works
    ubuntu: -- Detecting C compiler ABI info
    ubuntu: -- Detecting C compiler ABI info - done
    ubuntu: -- Detecting C compile features
    ubuntu: -- Detecting C compile features - done
    ubuntu: CMake Error at CMakeLists.txt:6 (project):
    ubuntu:   No CMAKE_CXX_COMPILER could be found.
    ubuntu:
    ubuntu:   Tell CMake where to find the compiler by setting either the environment
    ubuntu:   variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
    ubuntu:   to the compiler, or to the compiler name if it is in the PATH.
    ubuntu: -- Configuring incomplete, errors occurred!
```
I think this is related to @shaobo-he's recent updates.
